"""Point-and-click front end for the EMG pipeline.

Run it with:  streamlit run app.py

Everything happens on this computer — nothing is uploaded anywhere. That matters
because these are human-subjects recordings.

This is only a front end: every measurement comes from src/harmonize.py, the same
code the command line uses. If this app and the command line ever disagree, that is
a bug, not a setting.
"""
import sys
import tempfile
from pathlib import Path

import pandas as pd
import streamlit as st
import yaml

ROOT = Path(__file__).resolve().parent
sys.path.append(str(ROOT / "src"))
from harmonize import process_file, write_results, READABLE_DECIMALS, find_recordings
import selfcheck
import compare_legacy
import lineups

DEFAULT_MANIFEST = ROOT / "docs" / "Centralized-NIDAQ-System-Pharma-1957-PRIMING.xlsx"
DEFAULT_DATA = ROOT / "data" / "raw"
DEMO_DATA = ROOT / "data" / "demo"
DEMO_MANIFEST = DEMO_DATA / "demo-manifest.xlsx"
DEFAULT_CONFIG = ROOT / "config" / "params.yaml"


def folder_with_recordings():
    """Where to start looking: real recordings, then the synthetic set, then nowhere.

    A fresh clone has neither, since both are excluded from the repository. That is the
    normal state, and the app opens asking for a folder rather than complaining.
    """
    for candidate in (DEFAULT_DATA, DEMO_DATA):
        if candidate.exists() and any(candidate.rglob("*.csv")):
            return candidate
    return None


STARTING_FOLDER = folder_with_recordings()
DEMO_MODE = STARTING_FOLDER == DEMO_DATA

st.set_page_config(page_title="EMG pipeline", page_icon="⚡", layout="wide")
st.title("EMG pipeline")
st.caption("Measures every muscle's response to every stimulus pulse. "
           "Runs entirely on the machine it is installed on, no data leaves it.")

if DEMO_MODE:
    st.info(
        "**Synthetic recordings.** Generated by `python main.py demo`, with responses "
        "drawn at known latencies. No patient data is present. Point the folder box at "
        "your own recordings to measure those instead.",
        icon="🧪")
elif STARTING_FOLDER is None:
    st.info(
        "**No recordings found yet.** Type or paste the folder holding your `.csv` "
        "recordings in the box on the left. Subfolders are searched too. Nothing is "
        "uploaded anywhere; the files are read from this computer.",
        icon="📂")


def pick_folder():
    """Open the operating system's folder chooser.

    tkinter ships with Python, so it is inside the packaged Windows download too. This
    is what lets someone who has never opened a terminal point the tool at their data.
    """
    try:
        import tkinter as tk
        from tkinter import filedialog
        root = tk.Tk()
        root.withdraw()
        root.attributes("-topmost", True)      # otherwise it opens behind the browser
        chosen = filedialog.askdirectory(title="Choose the folder holding your recordings")
        root.destroy()
        return chosen or None
    except Exception:
        # no desktop available, e.g. running on a server; the text box still works
        return None


@st.cache_data(show_spinner=False)
def load_manifest(path, sheet):
    """Read the channel lineup workbook. Cached so it isn't re-read on every click."""
    return pd.read_excel(path, sheet_name=sheet)


def build_report(folder, manifest, settings):
    """The same self-check the command-line tool prints, as one block of text."""
    recordings = find_recordings(folder)
    has_sessions = any(selfcheck.session_from_path(r)["experiment"] is not None
                       for r in recordings)
    lines = [f"EMG PIPELINE SELF-CHECK", f"  {len(recordings)} recordings under {folder}"]
    lines += selfcheck.check_folders(recordings)
    lines += selfcheck.check_protocol_folders(recordings, has_sessions)
    lines += selfcheck.check_recordings(recordings, manifest, settings)[0]
    lines += [selfcheck.heading("PROVISIONAL COLUMNS"),
              "  These have never been checked against data known to be correct:",
              "    " + ", ".join(selfcheck.PROVISIONAL)]
    return "\n".join(lines)


# ---------------------------------------------------------------- settings
with st.sidebar:
    # This app runs on the machine it is installed on, so it can read folders directly.
    # That is the whole reason it handles a session the browser version cannot: nothing
    # is uploaded or copied, the recordings are read where they sit.
    st.header("1. Where the data is")

    if "chosen_folder" not in st.session_state:
        st.session_state.chosen_folder = str(STARTING_FOLDER or "")

    if st.button("Browse for a folder…", width="stretch"):
        picked = pick_folder()
        if picked:
            st.session_state.chosen_folder = picked

    data_folder = st.text_input("Folder of recordings",
                                value=st.session_state.chosen_folder,
                                placeholder="path to a folder of .csv recordings",
                                help="Subfolders are searched too. Point it at a session, "
                                     "a participant, or the whole store.")

    st.header("2. The channel lineup")
    st.caption("Which muscle each channel holds.")
    lineup_choice = st.selectbox(
        "Channel list", list(lineups.PRESETS) + ["From a spreadsheet"],
        index=list(lineups.PRESETS).index(lineups.DEFAULT))

    chosen_lineup, manifest_path, manifest_sheet = None, None, None
    if lineup_choice in lineups.PRESETS:
        chosen_lineup = lineups.PRESETS[lineup_choice]
        st.caption(lineups.describe(chosen_lineup))
        st.download_button("Save this lineup", lineups.to_json(chosen_lineup, lineup_choice),
                           "my-lineup.json", "application/json", width="stretch")
    else:
        # the workbook route: still the most accurate here, since it holds the exact
        # lineup for every session including those that differ from the standard
        manifest_path = st.text_input("Manifest workbook",
                                      value=str(DEMO_MANIFEST if DEMO_MODE else DEFAULT_MANIFEST))
        manifest_sheet = st.text_input("Sheet name", value="0" if DEMO_MODE else "draft-pharma")
        manifest_sheet = 0 if str(manifest_sheet).strip() in {"", "0"} else manifest_sheet

    st.header("3. Measurement settings")
    config = yaml.safe_load(open(DEFAULT_CONFIG))
    sampling_rate = st.number_input("Sampling rate (Hz)", value=config["sampling_rate_hz"], step=100)
    trigger_threshold = st.number_input("Trigger threshold (V)",
                                        value=float(config["trigger_threshold"]), step=0.5)

    st.caption("Measurement windows, in milliseconds from the stimulus.")
    prestim_start, prestim_end = config["windows_ms"]["prestim"]
    prestim_start = st.number_input("Pre-stimulus start", value=float(prestim_start))
    prestim_end = st.number_input("Pre-stimulus end", value=float(prestim_end))
    response_start, response_end = config["windows_ms"]["response"]["default"]
    response_start = st.number_input("Response start", value=float(response_start))
    response_end = st.number_input("Response end", value=float(response_end))
    st.caption(f"PNS keeps its own window "
               f"({config['windows_ms']['response'].get('PNS', ['—', '—'])[0]}–"
               f"{config['windows_ms']['response'].get('PNS', ['—', '—'])[1]} ms), "
               "because a peripheral M-wave arrives much sooner.")


def manifest_or_none():
    """The workbook, if that route was chosen. A picked lineup needs no workbook."""
    if chosen_lineup is not None:
        return None
    return load_manifest(manifest_path, manifest_sheet)


settings = {
    "sampling_rate_hz": sampling_rate,
    "trigger_threshold": trigger_threshold,
    "windows_ms": {
        "prestim": [prestim_start, prestim_end],
        "response": {**config["windows_ms"]["response"],
                     "default": [response_start, response_end]},
        "second_response": config["windows_ms"].get("second_response", {}),
    },
}

# ---------------------------------------------------------------- what was found
if not data_folder.strip():
    st.stop()          # nothing typed yet; the notice above says what to do

if not Path(data_folder).expanduser().exists():
    st.error(f"No such folder: {data_folder}")
    st.stop()
data_folder = str(Path(data_folder).expanduser())

recordings = find_recordings(data_folder)
if not recordings:
    st.warning(f"No .csv recordings found under {data_folder}")
    st.stop()

st.success(f"Found **{len(recordings)}** recordings under `{data_folder}`")
with st.expander("Show the file list"):
    st.write([f.name for f in recordings])

process_tab, check_tab, compare_tab = st.tabs(
    ["Process recordings", "Check my data", "Compare with the old pipeline"])

# ------------------------------------------------- compare with the MATLAB pipeline
with compare_tab:
    st.caption("Measures every recording twice — once the way the inherited MATLAB does it, "
               "once the way this pipeline does — so the two can be compared row for row. "
               "No MATLAB needed; nothing is uploaded.")
    if st.button("Run the comparison"):
        try:
            manifest = manifest_or_none()
        except Exception as e:
            st.error(f"Could not read the channel list: {e}")
        else:
            frames = []
            progress = st.progress(0.0, text="Measuring…")
            for i, rec in enumerate(recordings, start=1):
                progress.progress(i / len(recordings), text=f"{rec.name} ({i}/{len(recordings)})")
                try:
                    frames.append(compare_legacy.compare_recording(rec, manifest, settings))
                except Exception as e:
                    st.warning(f"skipped {rec.name}: {e}")
            progress.empty()

            if frames:
                comparison = pd.concat(frames, ignore_index=True)
                stats = compare_legacy.summarise(comparison)

                left, right = st.columns(2)
                left.metric("Peak-to-peak",
                            "identical" if stats["pk_pk_identical"] else "differs",
                            f"largest difference {stats['pk_pk_max_difference']:.1e}")
                right.metric("Area under curve",
                             f"{stats['auc_median_percent_change']:+.0f}%",
                             f"gap tracks electrode offset at r={stats['auc_gap_explained_by_offset']:.2f}")

                if stats["pk_pk_identical"]:
                    st.success("Peak-to-peak matches the old pipeline exactly, which means the "
                               "measurement windows, trigger detection and epoching all agree.")
                st.info("Area under curve differs because the old pipeline integrates the raw "
                        "trace while this one subtracts the pre-stimulus baseline first. The "
                        "table below shows how much of each old value was electrode offset "
                        "rather than muscle signal.")
                st.dataframe(compare_legacy.per_muscle(comparison), width="stretch")
                st.download_button("Download the comparison as text",
                                   compare_legacy.report(comparison),
                                   "comparison.txt", "text/plain")

# ---------------------------------------------------------------- check my data
with check_tab:
    st.caption("Runs the pipeline and reports what it found — folder names, triggers, "
               "skipped files, and whether the timing numbers look physiologically right. "
               "The report holds no EMG values and no patient details, so it is safe to share.")
    if st.button("Run the check"):
        try:
            manifest = manifest_or_none()
        except Exception as e:
            st.error(f"Could not read the channel list: {e}")
        else:
            with st.spinner("Checking…"):
                report = build_report(data_folder, manifest, settings)
            st.code(report, language="text")
            st.download_button("Download report.txt", report, "report.txt", "text/plain")

# ---------------------------------------------------------------- run
with process_tab:
    run = st.button("Process recordings", type="primary")

if run:
    try:
        manifest = manifest_or_none()
    except Exception as e:
        st.error(f"Could not read the channel list: {e}")
        st.stop()

    progress = st.progress(0.0, text="Starting…")
    frames, skipped = [], []

    for i, recording in enumerate(recordings, start=1):
        progress.progress(i / len(recordings), text=f"{recording.name}  ({i} of {len(recordings)})")
        try:
            frames.append(process_file(recording, manifest, settings))
        except Exception as e:
            skipped.append({"file": recording.name, "reason": str(e)})

    progress.empty()

    if not frames:
        st.error("Nothing could be processed. See the skipped list below.")
        st.dataframe(pd.DataFrame(skipped), width="stretch")
        st.stop()

    st.session_state["results"] = pd.concat(frames, ignore_index=True)
    st.session_state["skipped"] = pd.DataFrame(skipped)

# ---------------------------------------------------------------- results
if "results" in st.session_state:
    results = st.session_state["results"]
    skipped = st.session_state["skipped"]

    processed = len(recordings) - len(skipped)
    left, middle, right = st.columns(3)
    left.metric("Rows measured", f"{len(results):,}")
    middle.metric("Recordings processed", processed)
    right.metric("Recordings skipped", len(skipped))

    if len(skipped):
        st.subheader("Skipped recordings")
        st.caption("Grouped by reason — worth reading before trusting the results.")
        st.dataframe(skipped, width="stretch")

    st.subheader("Results")
    st.caption(f"Shown rounded to {READABLE_DECIMALS} decimal places; the download keeps "
               "full precision in the parquet file.")
    st.dataframe(results.round(READABLE_DECIMALS), width="stretch", height=400)

    with tempfile.TemporaryDirectory() as tmp:
        write_results(results, Path(tmp))
        csv_bytes = (Path(tmp) / "master_results.csv").read_bytes()
        parquet_bytes = (Path(tmp) / "master_results.parquet").read_bytes()

    left, right = st.columns(2)
    left.download_button("Download CSV (for Excel)", csv_bytes,
                         "master_results.csv", "text/csv", width="stretch")
    right.download_button("Download parquet (full precision)", parquet_bytes,
                          "master_results.parquet", "application/octet-stream", width="stretch")

    st.subheader("A quick look")
    order = results.groupby("muscle")["auc"].median().sort_values(ascending=False)
    st.bar_chart(order, x_label="median AUC", y_label="muscle", horizontal=True)
