"""Point-and-click front end for the EMG pipeline.

Run it with:  streamlit run app.py

Everything happens on this computer — nothing is uploaded anywhere. That matters
because these are human-subjects recordings.

This is only a front end: every measurement comes from src/harmonize.py, the same
code the command line uses. If this app and the command line ever disagree, that is
a bug, not a setting.
"""
import os
import subprocess
import sys
import tempfile
from pathlib import Path

import pandas as pd
import streamlit as st
import yaml

ROOT = Path(__file__).resolve().parent
sys.path.append(str(ROOT / "src"))
from harmonize import process_file, write_results, READABLE_DECIMALS, find_recordings
import selfcheck
import compare_legacy
import lineups

DEFAULT_MANIFEST = ROOT / "docs" / "Centralized-NIDAQ-System-Pharma-1957-PRIMING.xlsx"
DEFAULT_DATA = ROOT / "data" / "raw"
DEMO_DATA = ROOT / "data" / "demo"
DEMO_MANIFEST = DEMO_DATA / "demo-manifest.xlsx"
DEFAULT_CONFIG = ROOT / "config" / "params.yaml"


def folder_with_recordings():
    """Where to start looking: real recordings, then the synthetic set, then nowhere.

    A fresh clone has neither, since both are excluded from the repository. That is the
    normal state, and the app opens asking for a folder rather than complaining.
    """
    for candidate in (DEFAULT_DATA, DEMO_DATA):
        if candidate.exists() and any(candidate.rglob("*.csv")):
            return candidate
    return None


STARTING_FOLDER = folder_with_recordings()
DEMO_MODE = STARTING_FOLDER == DEMO_DATA

config = yaml.safe_load(open(DEFAULT_CONFIG))
WORK_IT_OUT = "Work it out from my recordings"

st.set_page_config(page_title="EMG pipeline (installed)", page_icon="⚡", layout="wide")
st.title("EMG pipeline")
st.caption("The installed version. Measures every muscle's response to every stimulus "
           "pulse.")
st.info(
    "**This is the program on your computer, not a website.** It draws its screen in a "
    "web browser, which is why the address bar says `localhost` — that word means this "
    "machine. Nothing is being sent anywhere.\n\n"
    "Because it runs here, it reads recordings straight off your hard drive: point it at "
    "a session, a participant, or the whole store, with no size limit.",
    icon="💻")

if DEMO_MODE:
    st.info(
        "**Synthetic recordings.** Generated by `python main.py demo`, with responses "
        "drawn at known latencies. No patient data is present. Point the folder box at "
        "your own recordings to measure those instead.",
        icon="🧪")
elif STARTING_FOLDER is None:
    st.info(
        "**No recordings found yet.** Type or paste the folder holding your `.csv` "
        "recordings in the box on the left. Subfolders are searched too. Nothing is "
        "uploaded anywhere; the files are read from this computer.",
        icon="📂")


CHOOSE_FOLDER_ON_MAC = '''
set chosen to choose folder with prompt "Choose the folder holding your recordings"
POSIX path of chosen
'''

CHOOSE_FOLDER_ON_WINDOWS = '''
Add-Type -AssemblyName System.Windows.Forms
$chooser = New-Object System.Windows.Forms.FolderBrowserDialog
$chooser.Description = "Choose the folder holding your recordings"
if ($chooser.ShowDialog() -eq [System.Windows.Forms.DialogResult]::OK) {
    Write-Output $chooser.SelectedPath
}
'''


def folder_chooser_command():
    """The command that opens this computer's folder chooser, or None if it has none.

    Each system already ships one, so nothing has to be installed for this to work.
    """
    if sys.platform == "darwin":
        return ["osascript", "-e", CHOOSE_FOLDER_ON_MAC]
    if os.name == "nt":
        return ["powershell", "-NoProfile", "-STA", "-Command", CHOOSE_FOLDER_ON_WINDOWS]
    return None


def pick_folder():
    """Open the folder chooser and return what was picked, or None.

    The chooser runs as a separate program rather than inside this one. A dialog has to
    own its program's main thread, and this app's main thread is busy serving the page,
    so opening one here freezes the app instead of showing a window.

    Clicking Cancel is not a problem, so it says nothing and changes nothing.
    """
    command = folder_chooser_command()
    if command is None:
        return pick_folder_the_old_way()

    quietly = {"creationflags": subprocess.CREATE_NO_WINDOW} if os.name == "nt" else {}
    try:
        # generous, but bounded: someone who walks away should not wedge the app
        finished = subprocess.run(command, capture_output=True, text=True,
                                  timeout=300, **quietly)
    except subprocess.TimeoutExpired:
        st.warning("The folder window was left open too long. Click Browse again, or "
                   "paste the folder in the box below.", icon="📂")
        return None
    except OSError as e:
        st.warning(f"The folder chooser would not open ({e}). Type or paste the folder "
                   "in the box below instead.", icon="📂")
        return None

    return finished.stdout.strip().splitlines()[0] if finished.stdout.strip() else None


def pick_folder_the_old_way():
    """For systems with no chooser of their own, such as Linux.

    In-process, so it carries the freezing problem described above. It stays only
    because the alternative on those systems is no button at all.
    """
    try:
        import tkinter as tk
        from tkinter import filedialog
    except ImportError:
        st.warning("This copy of the app was built without a folder chooser. Type or "
                   "paste the folder in the box below instead.", icon="📂")
        return None

    try:
        chooser = tk.Tk()
        chooser.withdraw()
        chooser.attributes("-topmost", True)   # otherwise it opens behind the browser
        chosen = filedialog.askdirectory(title="Choose the folder holding your recordings")
        chooser.destroy()
        return chosen or None
    except Exception as e:
        st.warning(f"The folder chooser would not open ({e}). Type or paste the folder "
                   "in the box below instead.", icon="📂")
        return None


@st.cache_data(show_spinner=False)
def which_copy_is_this():
    """Which build this is, so a stale copy cannot pass for a current one.

    A copy left running keeps serving the code it was built with, and looks identical to
    one built this minute. Saying so on screen is the difference between "the app is
    broken" and "this is an old copy".
    """
    stamped = ROOT / "build-info.txt"
    if stamped.exists():
        return stamped.read_text().strip()
    try:
        commit = subprocess.run(["git", "-C", str(ROOT), "rev-parse", "--short", "HEAD"],
                                capture_output=True, text=True, timeout=5).stdout.strip()
    except Exception:
        commit = ""
    return f"running from source, {commit}" if commit else "running from source"


@st.cache_data(show_spinner=False)
def recordings_in(folder):
    """The recordings under a folder, or none if it does not exist yet."""
    path = Path(folder).expanduser() if folder.strip() else None
    return find_recordings(path) if path and path.exists() else []


@st.cache_data(show_spinner="Reading a few recordings to see which channel list fits…")
def which_lineups_fit(folder):
    """Cached on the folder, so it reads the files once rather than on every click."""
    return lineups.that_fit(recordings_in(folder), config)


@st.cache_data(show_spinner=False)
def load_manifest(path, sheet):
    """Read the channel lineup workbook. Cached so it isn't re-read on every click."""
    return pd.read_excel(path, sheet_name=sheet)


def build_report(folder, manifest, settings, lineup=None):
    """The same self-check the command-line tool prints, as one block of text."""
    recordings = find_recordings(folder)
    has_sessions = any(selfcheck.session_from_path(r)["experiment"] is not None
                       for r in recordings)
    lines = [f"EMG PIPELINE SELF-CHECK", f"  {len(recordings)} recordings under {folder}"]
    lines += selfcheck.check_folders(recordings)
    lines += selfcheck.check_protocol_folders(recordings, has_sessions)
    lines += selfcheck.check_recordings(recordings, manifest, settings, lineup)[0]
    lines += [selfcheck.heading("PROVISIONAL COLUMNS"),
              "  These have never been checked against data known to be correct:",
              "    " + ", ".join(selfcheck.PROVISIONAL)]
    return "\n".join(lines)


# ---------------------------------------------------------------- settings
with st.sidebar:
    # This app runs on the machine it is installed on, so it can read folders directly.
    # That is the whole reason it handles a session the browser version cannot: nothing
    # is uploaded or copied, the recordings are read where they sit.
    st.header("1. Where the data is")

    if "chosen_folder" not in st.session_state:
        st.session_state.chosen_folder = str(STARTING_FOLDER or "")

    if st.button("Browse for a folder…", width="stretch"):
        picked = pick_folder()
        if picked:
            st.session_state.chosen_folder = picked

    data_folder = st.text_input("Folder of recordings",
                                value=st.session_state.chosen_folder,
                                placeholder="path to a folder of .csv recordings",
                                help="Subfolders are searched too. Point it at a session, "
                                     "a participant, or the whole store.")

    found_recordings = recordings_in(data_folder)

    st.header("2. The channel lineup")
    st.caption("Which muscle each channel holds.")
    lineup_choice = st.selectbox(
        "Channel list", [WORK_IT_OUT] + list(lineups.PRESETS) + ["From a spreadsheet"])

    chosen_lineup, manifest_path, manifest_sheet = None, None, None

    if lineup_choice == WORK_IT_OUT and found_recordings:
        # The recording says which channels carry stimulus pulses, so a list that calls
        # one of them a muscle is provably the wrong list for this equipment.
        fitting = which_lineups_fit(data_folder)
        if fitting:
            lineup_choice = fitting[0]
            st.success(f"**{lineup_choice}**", icon="✅")
            st.caption("Chosen because the channels carrying stimulus pulses in your "
                       "recordings match it. Pick one yourself above if you would rather.")
        else:
            st.error(
                "None of the built-in channel lists matches these recordings: the "
                "channels carrying stimulus pulses are not where any of them expect. "
                "Choose **From a spreadsheet** and give it your own channel list.",
                icon="🔌")
    elif lineup_choice == WORK_IT_OUT:
        st.caption("Choose a folder above and this will work out which list fits.")

    if lineup_choice in lineups.PRESETS:
        chosen_lineup = lineups.PRESETS[lineup_choice]
        st.caption(lineups.describe(chosen_lineup))
        st.download_button("Save this lineup", lineups.to_json(chosen_lineup, lineup_choice),
                           "my-lineup.json", "application/json", width="stretch")
    elif lineup_choice != WORK_IT_OUT:
        # the workbook route: still the most accurate here, since it holds the exact
        # lineup for every session including those that differ from the standard
        manifest_path = st.text_input("Manifest workbook",
                                      value=str(DEMO_MANIFEST if DEMO_MODE else DEFAULT_MANIFEST))
        manifest_sheet = st.text_input("Sheet name", value="0" if DEMO_MODE else "draft-pharma")
        manifest_sheet = 0 if str(manifest_sheet).strip() in {"", "0"} else manifest_sheet

    st.header("3. Measurement settings")
    sampling_rate = st.number_input("Sampling rate (Hz)", value=config["sampling_rate_hz"], step=100)
    trigger_threshold = st.number_input("Trigger threshold (V)",
                                        value=float(config["trigger_threshold"]), step=0.5)

    st.caption("Measurement windows, in milliseconds from the stimulus.")
    prestim_start, prestim_end = config["windows_ms"]["prestim"]
    prestim_start = st.number_input("Pre-stimulus start", value=float(prestim_start))
    prestim_end = st.number_input("Pre-stimulus end", value=float(prestim_end))
    response_start, response_end = config["windows_ms"]["response"]["default"]
    response_start = st.number_input("Response start", value=float(response_start))
    response_end = st.number_input("Response end", value=float(response_end))
    st.caption(f"PNS keeps its own window "
               f"({config['windows_ms']['response'].get('PNS', ['—', '—'])[0]}–"
               f"{config['windows_ms']['response'].get('PNS', ['—', '—'])[1]} ms), "
               "because a peripheral M-wave arrives much sooner.")

    st.divider()
    st.caption(f"This copy: {which_copy_is_this()}")


def manifest_or_none():
    """The workbook, if that route was chosen. A picked lineup needs no workbook."""
    if chosen_lineup is not None:
        return None
    if manifest_path is None:
        raise ValueError("No channel list chosen yet: pick one in the sidebar, or let it "
                         "be worked out from the recordings.")
    return load_manifest(manifest_path, manifest_sheet)


settings = {
    "sampling_rate_hz": sampling_rate,
    "trigger_threshold": trigger_threshold,
    "windows_ms": {
        "prestim": [prestim_start, prestim_end],
        "response": {**config["windows_ms"]["response"],
                     "default": [response_start, response_end]},
        "second_response": config["windows_ms"].get("second_response", {}),
    },
}

# ---------------------------------------------------------------- what was found
if not data_folder.strip():
    st.stop()          # nothing typed yet; the notice above says what to do

if not Path(data_folder).expanduser().exists():
    st.error(f"No such folder: {data_folder}")
    st.stop()
data_folder = str(Path(data_folder).expanduser())

recordings = find_recordings(data_folder)
if not recordings:
    st.warning(f"No .csv recordings found under {data_folder}")
    st.stop()

st.success(f"Found **{len(recordings)}** recordings under `{data_folder}`")
with st.expander("Show the file list"):
    st.write([f.name for f in recordings])

process_tab, check_tab, compare_tab = st.tabs(
    ["Process recordings", "Check my data", "Compare with the old pipeline"])

# ------------------------------------------------- compare with the MATLAB pipeline
with compare_tab:
    st.caption("Measures every recording twice — once the way the inherited MATLAB does it, "
               "once the way this pipeline does — so the two can be compared row for row. "
               "No MATLAB needed; nothing is uploaded.")
    if st.button("Run the comparison"):
        try:
            manifest = manifest_or_none()
        except Exception as e:
            st.error(f"Could not read the channel list: {e}")
        else:
            frames = []
            progress = st.progress(0.0, text="Measuring…")
            for i, rec in enumerate(recordings, start=1):
                progress.progress(i / len(recordings), text=f"{rec.name} ({i}/{len(recordings)})")
                try:
                    frames.append(compare_legacy.compare_recording(
                        rec, manifest, settings, lineup=chosen_lineup))
                except Exception as e:
                    st.warning(f"skipped {rec.name}: {e}")
            progress.empty()

            if frames:
                comparison = pd.concat(frames, ignore_index=True)
                stats = compare_legacy.summarise(comparison)

                left, right = st.columns(2)
                left.metric("Peak-to-peak",
                            "identical" if stats["pk_pk_identical"] else "differs",
                            f"largest difference {stats['pk_pk_max_difference']:.1e}")
                right.metric("Area under curve",
                             f"{stats['auc_median_percent_change']:+.0f}%",
                             f"gap tracks electrode offset at r={stats['auc_gap_explained_by_offset']:.2f}")

                if stats["pk_pk_identical"]:
                    st.success("Peak-to-peak matches the old pipeline exactly, which means the "
                               "measurement windows, trigger detection and epoching all agree.")
                st.info("Area under curve differs because the old pipeline integrates the raw "
                        "trace while this one subtracts the pre-stimulus baseline first. The "
                        "table below shows how much of each old value was electrode offset "
                        "rather than muscle signal.")
                st.dataframe(compare_legacy.per_muscle(comparison), width="stretch")
                st.download_button("Download the comparison as text",
                                   compare_legacy.report(comparison),
                                   "comparison.txt", "text/plain")

# ---------------------------------------------------------------- check my data
with check_tab:
    st.caption("Runs the pipeline and reports what it found — folder names, triggers, "
               "skipped files, and whether the timing numbers look physiologically right. "
               "The report holds no EMG values and no patient details, so it is safe to share.")
    if st.button("Run the check"):
        try:
            manifest = manifest_or_none()
        except Exception as e:
            st.error(f"Could not read the channel list: {e}")
        else:
            with st.spinner("Checking…"):
                report = build_report(data_folder, manifest, settings, chosen_lineup)
            st.code(report, language="text")
            st.download_button("Download report.txt", report, "report.txt", "text/plain")

# ---------------------------------------------------------------- run
with process_tab:
    run = st.button("Process recordings", type="primary")

if run:
    try:
        manifest = manifest_or_none()
    except Exception as e:
        st.error(f"Could not read the channel list: {e}")
        st.stop()

    progress = st.progress(0.0, text="Starting…")
    frames, skipped = [], []

    for i, recording in enumerate(recordings, start=1):
        progress.progress(i / len(recordings), text=f"{recording.name}  ({i} of {len(recordings)})")
        try:
            frames.append(process_file(recording, manifest, settings,
                                       lineup=chosen_lineup))
        except Exception as e:
            skipped.append({"file": recording.name, "reason": str(e)})

    progress.empty()

    if not frames:
        # By far the most common cause, and the least obvious from a list of reasons:
        # the wrong channel list. Say that plainly rather than making it be deduced.
        if all("does not match" in row["reason"] for row in skipped):
            fitting = which_lineups_fit(data_folder)
            st.error(
                f"**The channel list is wrong for these recordings.** `{lineup_choice}` "
                "says a muscle sits on a channel that is actually carrying stimulus "
                "pulses, so every measurement would come out under the wrong muscle. "
                "Nothing was measured rather than measured wrongly.\n\n"
                + (f"**Choose _{fitting[0]}_ instead**, which does match."
                   if fitting else
                   "None of the built-in lists matches these recordings either, so the "
                   "channel list needs to come from your own spreadsheet."),
                icon="🔌")
        else:
            st.error("Nothing could be processed. See the reasons below.")
        st.dataframe(pd.DataFrame(skipped), width="stretch")
        st.stop()

    st.session_state["results"] = pd.concat(frames, ignore_index=True)
    st.session_state["skipped"] = pd.DataFrame(skipped)

# ---------------------------------------------------------------- results
if "results" in st.session_state:
    results = st.session_state["results"]
    skipped = st.session_state["skipped"]

    processed = len(recordings) - len(skipped)
    left, middle, right = st.columns(3)
    left.metric("Rows measured", f"{len(results):,}")
    middle.metric("Recordings processed", processed)
    right.metric("Recordings skipped", len(skipped))

    if len(skipped):
        st.subheader("Skipped recordings")
        st.caption("Grouped by reason — worth reading before trusting the results.")
        st.dataframe(skipped, width="stretch")

    st.subheader("Results")
    st.caption(f"Shown rounded to {READABLE_DECIMALS} decimal places; the download keeps "
               "full precision in the parquet file.")
    st.dataframe(results.round(READABLE_DECIMALS), width="stretch", height=400)

    with tempfile.TemporaryDirectory() as tmp:
        write_results(results, Path(tmp))
        csv_bytes = (Path(tmp) / "master_results.csv").read_bytes()
        parquet_bytes = (Path(tmp) / "master_results.parquet").read_bytes()

    left, right = st.columns(2)
    left.download_button("Download CSV (for Excel)", csv_bytes,
                         "master_results.csv", "text/csv", width="stretch")
    right.download_button("Download parquet (full precision)", parquet_bytes,
                          "master_results.parquet", "application/octet-stream", width="stretch")

    st.subheader("A quick look")
    order = results.groupby("muscle")["auc"].median().sort_values(ascending=False)
    st.bar_chart(order, x_label="median AUC", y_label="muscle", horizontal=True)
